#!/bin/sh


# provides $IN_OPTS
. profiles/input/infracam_rtsp
# provides QUALITY_OPTS
. profiles/quality/640_low_ultrafast
# provides $OUT_OPTS $OUT_URL
#. profiles/output/ustream_infracam
. profiles/output/justintv_instacam
FFMPEG=/usr/bin/ffmpeg
PATH=$PATH:/krebs/util/bin


while sleep 1;do
	now=$(timer)
#	pkill -9 ffmpeg
	$FFMPEG  -re $IN_OPTS  $QUALITY_OPTS $OUT_OPTS "$OUT_URL" -loglevel info
	then=$(timer $now)
        echo "$FFMPEG running for $then ms"
        GRAPHITE_HOST=no_omo graphitec shack.streamer.instacam.runtime $then
#trap "kill $$" INT QUIT TERM EXIT
done
